services:
  redis:
    image: redis:alpine3.22
    container_name: usefulkey-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 2s
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: usefulkey-postgres
    environment:
      POSTGRES_DB: usefulkey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usefulkey"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: usefulkey-net

volumes:
  postgres_data:
